# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8456ae33fb7a2c866c9b765d778b1effc4bbf29997103c88d6988852f013ab3110939f86cc150e9ed42c2bb4c5e2c2de61869bc0db786a27b9f29d119ec9123d

test:
  secret_key_base: dff888462c2ae2938369c33ae64d197116f95caa78b810e608816749113e0a0da05eae0d2be53c50045419f4cf456876777800a2433d21999a24f300bfa03420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
